### ISSUE TITLE
Allow multiple broadcast data passed to listener

### ISSUE THREAD

**Issue by yslyong** [mojjominion/barcode-broadcast-receiver#14]
I make a temporary package for this issue
https://github.com/yslyong/react-native-broadcast-receiver-android

once the fixes deployed, i will delete the duplicated package and repo

Root causes of this issue is when one action is broadcasting multiple value in single broadcast, unable to get multiple in the same action.

Example:
`adb shell am broadcast -a com.action.data --es epc "EPC_VALUE" --es tid "TID_VALUE" --es rssi "RSSI_VALUE"`

Usage:
When datakey exist it will only get the data for datakey, if datakey is empty string the listener will return the full broadcast data to the listener.
```
        BroadcastReceiver.setIntentActionConfig([
            { action: "com.showdecode.data", datakey: "msg" },
            { action: "com.action.data", datakey: "" },
        ])
```

**Comment by mojjominion** [comment]
@yslyong Thank you for reporting this and raising the PR.

A new version [0.6.0](https://github.com/mojjominion/react-native-broadcast-receiver/compare/v0.5.0...v0.6.0) is released with these changes.

**Comment by daisy-i** [comment]
@mojjominion Hello!  Can you add a function to send broadcasts? I tried using patch-package@8.0.0 to create patches, but my method may not have been successful

**Comment by mojjominion** [comment]
@daisy-i checkout the `broadcast` commands here [package.json](https://github.com/mojjominion/react-native-broadcast-receiver/blob/64408012f402031595d8f5a3637b80a8be226136/example/package.json#L10).

If this is not what you wanted, can  you paste here what you have tried so far?
