### ISSUE TITLE
Differentiate between datakeys?

### ISSUE THREAD

**Issue by brsnik** [mojjominion/barcode-broadcast-receiver#7]
In the case of having two listeners used for different tasks, how can I differentiate between them?

For example:
```
BroadcastReceiver.setIntentActionConfig([
    { action: 'com.app.barcode', datakey: 'barcode' },
    { action: 'com.app.rfid', datakey: 'rfid' },
]);
```

The event listener only returns `data` regardless of what the `datakey` is named.

**Comment by mojjominion** [comment]
Right. I believe an object can be thrown back containing the relevant data, in this case `dataKey` and  `data` itself. After that is done javascript side will require integration changes to read the newly defined payload.
